name: local-action

inputs:
  field0:
    description: field0
    required: false
  field1:
    description: field0
    required: false

runs:
  using: composite
  steps:
    - name: dump env
      shell: bash
      run: |
        env | wc -l
        env
        cat $GITHUB_ACTION_PATH

    - name: dump env
      shell: bash
      run: ${GITHUB_ACTION_PATH}/foo.sh
      env:
        FIELD0: ${{ env.FIELD0 || github.event.pull_request.head.sha }}
