name: Trunk Check (service)
on:
  workflow_dispatch:
    inputs:
      client_payload:
        required: true

jobs:
  check:
    name: ${{ fromJSON(inputs.client_payload).check_job_name }}
    runs-on: ubuntu-latest
    if: fromJSON(inputs.client_payload).version == '0.0.0'

    steps:
      - name: Apply token masks
        shell: bash
        run: |
          echo "::add-mask::$INPUT_GITHUB_TOKEN"
          echo "::add-mask::$INPUT_TOKEN"
        env:
          INPUT_GITHUB_TOKEN: ${{ fromJSON(inputs.client_payload).githubToken }}
          INPUT_TOKEN: ${{ fromJSON(inputs.client_payload).token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(inputs.client_payload).target.name }}
          ref: ${{ fromJSON(inputs.client_payload).target.ref_sha }}
          token: ${{ fromJSON(inputs.client_payload).github_token }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
        with:
          json: ${{ inputs.client_payload }}
