name: trunk
on:
  workflow_dispatch:
    inputs:
      client_payload:
        required: true

jobs:
  check:
    name: Trunk Check
    uses: trunk-io/trunk-action/.github/workflows/check-service.reusable.yaml@sam/check-dot-trunk
