name: trunk
on:
  workflow_dispatch:
    inputs:
      client_payload:
        required: true

jobs:
  check:
    name: Trunk Check
    runs-on: ubuntu-latest
  
    steps:
      - name: Trunk Check
        uses: trunk-io/trunk-action/check-service@sam/check-dot-trunk
        with:
          client_payload: ${{ inputs.client_payload }}
