name: Trunk Check (service)
on:
  workflow_dispatch:
    inputs:
      client_payload:
        required: true

jobs:
  check:
    name: ${{ fromJSON(inputs.client_payload).checkJobName }}
    runs-on: ubuntu-latest
    if: fromJSON(inputs.client_payload).version == '0.0.0'

    steps:
      - name: Apply token masks
        shell: bash
        run: |
          echo "::add-mask::$(jq .githubToken $GITHUB_EVENT_PATH)"
          echo "::add-mask::$(jq .token $GITHUB_EVENT_PATH)"
          cat $GITHUB_EVENT_PATH

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(inputs.client_payload).target.name }}
          ref: ${{ fromJSON(inputs.client_payload).target.refSha }}
          token: ${{ fromJSON(inputs.client_payload).githubToken }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@main
        with:
          json: ${{ inputs.client_payload }}
